FROM python:3.12

# Set the working directory in the container
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    libffi-dev \
    python3-dev \
    git \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    g++ \
    && rm -rf /var/lib/apt/lists/*

# Install TensorQTL dependencies
RUN pip3 install cython
RUN pip3 install pgenlib
RUN pip3 install tensorqtl
